sylius_twig_hooks:
    hooks:
        'sylius_admin.blacklisting_rule.create.content':
            form:
                component: 'sylius_admin:blacklisting_rule:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@BitBagSyliusBlacklistPlugin/BlacklistingRule/Admin/form.html.twig'
                configuration:
                    render_rest: false
