bitbag_sylius_blacklist_plugin_admin:
    resource: "@BitBagSyliusBlacklistPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

bitbag_sylius_blacklist_plugin_shop:
    resource: "@BitBagSyliusBlacklistPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}