sylius_resource:
  resources:
    bitbag_sylius_blacklist_plugin.automatic_blacklisting_configuration:
      classes:
        model: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\AutomaticBlacklistingConfiguration
        repository: BitBag\SyliusBlacklistPlugin\Repository\AutomaticBlacklistingConfigurationRepository
        interface: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\AutomaticBlacklistingConfigurationInterface
        form: BitBag\SyliusBlacklistPlugin\Form\Type\AutomaticBlacklistingConfigurationType