sylius_resource:
  resources:
    bitbag_sylius_blacklist_plugin.blacklisting_rule:
      classes:
        model: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\BlacklistingRule
        interface: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\BlacklistingRule