sylius_resource:
    resources:
        bitbag_sylius_blacklist_plugin.fraud_suspicion:
            classes:
                model: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\FraudSuspicion
                form: BitBag\SyliusBlacklistPlugin\Form\Type\FraudSuspicionType
                repository: BitBag\SyliusBlacklistPlugin\Repository\FraudSuspicionRepository
