sylius_resource:
    resources:
        bitbag_sylius_blacklist_plugin.fraud_suspicion:
            classes:
                model: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\FraudSuspicion
                repository: BitBag\SyliusBlacklistPlugin\Repository\FraudSuspicionRepository
                interface: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\FraudSuspicionInterface
                factory: BitBag\SyliusBlacklistPlugin\Factory\FraudSuspicionFactory
                form: BitBag\SyliusBlacklistPlugin\Form\Type\FraudSuspicionType