sylius_resource:
    resources:
        bitbag_sylius_blacklist_plugin.fraud_suspicion:
            classes:
                model: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\FraudSuspicion
                interface: BitBag\SyliusBlacklistPlugin\Entity\FraudPrevention\FraudSuspicionInterface
                form: BitBag\SyliusBlacklistPlugin\Form\Type\FraudSuspicionType