sylius_grid:
  grids:
    sylius_admin_customer:
      driver:
        name: doctrine/orm
        options:
          class: Tests\BitBag\SyliusBlacklistPlugin\Entity\Customer
      sorting:
        createdAt: desc
      fields:
        firstName:
          type: string
          label: sylius.ui.first_name
          sortable: ~
        lastName:
          type: string
          label: sylius.ui.last_name
          sortable: ~
        email:
          type: string
          label: sylius.ui.email
          sortable: ~
        createdAt:
          type: datetime
          label: sylius.ui.registration_date
          sortable: ~
          options:
            format: d-m-Y H:i
        enabled:
          type: twig
          label: sylius.ui.enabled
          path: .
          options:
            template: "@SyliusAdmin/Customer/Grid/Field/enabled.html.twig"
        verified:
          type: twig
          label: sylius.ui.verified
          path: .
          options:
            template: "@SyliusAdmin/Customer/Grid/Field/verified.html.twig"
        fraudStatus:
          type: twig
          label: bitbag_sylius_blacklist_plugin.ui.fraud_status
          options:
            template: "@BitBagSyliusBlacklistPlugin/Customer/Grid/Field/fraudStatus.html.twig"
      filters:
        fraudStatus:
          type: select
          label: bitbag_sylius_blacklist_plugin.ui.fraud_status
          form_options:
            choices:
              bitbag_sylius_blacklist_plugin.ui.neutral: Neutral
              bitbag_sylius_blacklist_plugin.ui.blacklisted: Blacklisted
        search:
          type: string
          label: sylius.ui.search
          options:
            fields: [email, firstName, lastName]
      actions:
        main:
          create:
            type: create
        item:
          show_orders:
            type: show
            label: sylius.ui.show_orders
            options:
              link:
                route: sylius_admin_customer_order_index
                parameters:
                  id: resource.id
          show:
            type: show
          update:
            type: update