bitbag_sylius_blacklist_plugin_admin_blacklisting_rule:
    resource: |
        alias: bitbag_sylius_blacklist_plugin.blacklisting_rule
        section: admin
        templates: "@SyliusAdmin/Crud"
        grid: bitbag_sylius_blacklist_plugin_blacklisting_rule
        except: ['show']
        permission: true
        vars:
            all:
                subheader: bitbag_sylius_blacklist_plugin.ui.manage_blacklisting_rules
                templates:
                    form: "@BitBagSyliusBlacklistPlugin/BlacklistingRule/Admin/_form.html.twig"
            index:
                icon: clipboard list
    type: sylius.resource
