bitbag_sylius_blacklist_plugin_admin_blacklisting_rule:
    resource: |
        alias: bitbag_sylius_blacklist_plugin.blacklisting_rule
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: bitbag_sylius_blacklist_plugin_blacklisting_rule
        only: ['index', 'update', 'create', 'delete']
        permission: true
        vars:
            all:
                subheader: bitbag_sylius_blacklist_plugin.ui.manage_blacklisting_rules
            index:
                icon: clipboard list
    type: sylius.resource
