bitbag_sylius_blacklist_plugin_admin_fraud_suspicion:
    resource: |
        alias: bitbag_sylius_blacklist_plugin.fraud_suspicion
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        grid: bitbag_sylius_blacklist_plugin_fraud_suspicion
        permission: true
        vars:
            all:
                subheader: bitbag_sylius_blacklist_plugin.ui.manage_fraud_suspicions
            index:
                icon: clipboard list
    type: sylius.resource

sylius_admin_fraud_suspicion_show:
    path: fraud-suspicions/{id}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_blacklist_plugin.controller.fraud_suspicion::showAction
        _sylius:
            template: "@BitBagSyliusBlacklistPlugin/FraudSuspicion/Admin/show.html.twig"
            criteria:
                id: $id

bitbag_sylius_blacklist_plugin_admin_order_mark_suspicious:
    path: /order/{orderId}/fraud-suspicion/new
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_blacklist_plugin.controller.fraud_suspicion::createAction
        _sylius:
            vars:
                route:
                    name: bitbag_sylius_blacklist_plugin_admin_order_mark_suspicious
                    parameters:
                        orderId: $orderId
            section: admin
            template: "@SyliusAdmin/shared/crud/create.html.twig"
            factory:
                method: createForOrder
                arguments:
                    - "expr:notFoundOnNull(service('sylius.repository.order').find($orderId))"

bitbag_sylius_blacklist_plugin_admin_ajax_customer_by_email:
    path: /customer-search
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findByEmailPart
                arguments:
                    email: $email
                    limit: "!!int %bitbag.ajax.customer.autocomplete_limit%"

bitbag_sylius_blacklist_plugin_admin_ajax_customer_by_id:
    path: /customer-search-by-id
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findBy
                arguments: [id: $id]
