sylius_twig_hooks:
    hooks:
        'sylius_admin.fraud_suspicion.create.content':
            form:
                component: 'sylius_admin:fraud_suspicion:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@BitBagSyliusBlacklistPlugin/FraudSuspicion/Admin/form.html.twig'
                configuration:
                    render_rest: false
